baseURL = 'https://tylerdomitrovich.com/'
languageCode = 'en-us'
title = 'Tyler Domtrovich'
theme = 'hugo-theme-nix'
canonifyURLs = true

[params]
  Name = "Tyler Domitrovich"
  HeaderUsername = "tyler"
  HeaderHostname = "website"
  About = "Hi, I'm Tyler. I enjoy building and fixing software, and learning along the way."
  ProfilePicture = "/mountain_tyler.png"
  GithubID = "tydomitrovich"
  Email = "tydomit@gmail.com"
  LinkedInId = "tyler-domitrovich"
